name: oracle-ai-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - flask>=3.0.0
  - pyyaml>=6.0
  - pytest>=7.0.0
  - requests>=2.31.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - joblib>=1.3.0
  - pip
  - pip:
    - cx_Oracle==8.3
    - python-dotenv>=1.0.0
    - gunicorn>=21.0.0
    - pytest-cov>=4.0.0
    - black>=23.0.0
    - flake8>=6.0.0
    - pre-commit>=3.0.0 