# Retail Sales Insight & Top Category Dashboard Configuration

# Data Paths
data_paths:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  output_file: "data/processed/sales_insights.csv"

# Business Logic Settings
business_logic:
  category_threshold: 1000  # Minimum sales amount to be considered "top category"
  top_categories_limit: 5   # Number of top categories to return

# API Configuration
api:
  host: "0.0.0.0"
  port: 5000
  debug: false

# Oracle Cloud Deployment
oracle_server:
  host: "139.185.33.139"
  user: "ubuntu"
  target_dir: "/home/ubuntu/ai-project-template"

# Data Validation
data_validation:
  required_columns: ["Date", "Product Category", "Total Amount"]
  expected_dtypes:
    Date: "object"
    Product Category: "object"
    Total Amount: "float64"

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 