# Oracle Server Kafka Configuration for ML Pipeline System

kafka:
  # Bootstrap servers for Oracle deployment
  bootstrap_servers: "139.185.33.139:9092"
  
  # External listeners for remote connections
  external_bootstrap_servers: "139.185.33.139:29092"
  
  # Security settings
  security_protocol: "PLAINTEXT"  # PLAINTEXT, SASL_PLAINTEXT, SASL_SSL, SSL
  sasl_mechanism: "PLAIN"  # PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
  
  # Authentication (if using SASL)
  # sasl_username: ""
  # sasl_password: ""
  
  # SSL settings (if using SSL)
  ssl_cafile: ""
  ssl_certfile: ""
  ssl_keyfile: ""
  ssl_password: ""

# Topics configuration for Oracle deployment
topics:
  # Data ingestion topics
  raw_data_topic: "ml-pipeline-raw-data"
  processed_data_topic: "ml-pipeline-processed-data"
  
  # Model training topics
  model_training_topic: "ml-pipeline-model-training"
  model_evaluation_topic: "ml-pipeline-model-evaluation"
  
  # Prediction topics
  prediction_requests_topic: "ml-pipeline-prediction-requests"
  prediction_results_topic: "ml-pipeline-prediction-results"
  
  # Monitoring topics
  pipeline_monitoring_topic: "ml-pipeline-monitoring"
  model_monitoring_topic: "ml-pipeline-model-monitoring"
  
  # Alert topics
  alerts_topic: "ml-pipeline-alerts"
  
  # Dead letter queue
  dead_letter_topic: "ml-pipeline-dead-letter"

# Producer settings optimized for Oracle deployment
producer:
  acks: "all"  # 0, 1, or "all"
  retries: 3
  batch_size: 16384
  linger_ms: 5
  buffer_memory: 33554432
  compression_type: "snappy"  # none, gzip, snappy, lz4, zstd
  max_request_size: 1048576
  request_timeout_ms: 30000
  # Oracle-specific settings
  max_block_ms: 60000
  delivery_timeout_ms: 120000

# Consumer settings optimized for Oracle deployment
consumer:
  group_id: "ml-pipeline-consumer-group"
  auto_offset_reset: "earliest"  # earliest, latest
  enable_auto_commit: true
  auto_commit_interval_ms: 5000
  session_timeout_ms: 30000
  heartbeat_interval_ms: 3000
  max_poll_records: 500
  fetch_max_wait_ms: 500
  fetch_min_bytes: 1
  fetch_max_bytes: 52428800
  # Oracle-specific settings
  max_poll_interval_ms: 300000
  request_timeout_ms: 30000

# Schema Registry (if using Avro)
schema_registry:
  url: "http://139.185.33.139:8081"
  enabled: false

# Monitoring and metrics for Oracle deployment
monitoring:
  enabled: true
  metrics_interval_seconds: 60
  health_check_interval_seconds: 30
  # Oracle-specific monitoring
  log_level: "INFO"
  enable_jmx: true
  jmx_port: 9101
  
# Error handling for Oracle deployment
error_handling:
  max_retries: 3
  retry_delay_seconds: 5
  dead_letter_topic: "ml-pipeline-dead-letter"
  enable_dead_letter_queue: true
  # Oracle-specific error handling
  enable_circuit_breaker: true
  circuit_breaker_threshold: 5
  circuit_breaker_timeout: 60

# Performance tuning for Oracle deployment
performance:
  producer_threads: 2
  consumer_threads: 4
  batch_processing_size: 1000
  processing_timeout_seconds: 300
  # Oracle-specific performance settings
  max_memory_mb: 2048
  gc_optimization: true

# Oracle deployment specific settings
oracle_deployment:
  # Server information
  server_ip: "139.185.33.139"
  server_hostname: "oracle-ml-server"
  
  # Service management
  kafka_service_name: "kafka.service"
  zookeeper_service_name: "zookeeper.service"
  
  # Paths
  kafka_home: "/opt/kafka"
  kafka_data_dir: "/var/lib/kafka/data"
  kafka_log_dir: "/var/log/kafka"
  zookeeper_data_dir: "/var/lib/zookeeper/data"
  zookeeper_log_dir: "/var/log/zookeeper"
  
  # User and group
  kafka_user: "kafka"
  kafka_group: "kafka"
  
  # Network configuration
  internal_port: 9092
  external_port: 29092
  zookeeper_port: 2181
  
  # Security
  firewall_enabled: true
  allowed_ips: []
  
  # Backup and maintenance
  backup_enabled: true
  backup_retention_days: 7
  log_retention_days: 7
  
  # Health monitoring
  health_check_enabled: true
  health_check_interval: 300  # seconds
  alert_on_failure: true 