name: Oracle Data Preprocessing

on:
  workflow_dispatch:      # Manual run
  schedule:
    - cron: '0 0 * * *'    # Every day at 12 AM UTC

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Extract data from Oracle
      run: python src/preprocess.py
      env:
        ORACLE_HOST: ${{ secrets.ORACLE_HOST }}
        ORACLE_PORT: ${{ secrets.ORACLE_PORT }}
        ORACLE_USER: ${{ secrets.ORACLE_USER }}
        ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
        ORACLE_SERVICE_NAME: ${{ secrets.ORACLE_SERVICE_NAME }}

    - name: Feature Engineering
      run: python src/feature_engineering.py

    # TODO: Uncomment this when features.csv is ready and needs to be shared
    # - name: Upload processed data
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: features-csv
    #     path: data/features/features.csv
