name: Quick Test

on:
  workflow_dispatch:

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ORACLE_SSH_KEY }}" > ~/.ssh/oracle.key
          chmod 600 ~/.ssh/oracle.key
          ssh-keyscan -H 139.185.33.139 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/oracle.key ubuntu@139.185.33.139 "echo '✅ SSH connection successful'; uname -a"

      - name: Install rsync on runner
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync
          echo "✅ rsync installed on runner"

      - name: Test rsync functionality
        run: |
          echo "🔄 Testing rsync..."
          rsync --version
          echo "✅ rsync is working"

      - name: Check server rsync
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/oracle.key ubuntu@139.185.33.139 << 'EOF'
            echo "🔧 Checking rsync on server..."
            if command -v rsync >/dev/null 2>&1; then
              echo "✅ rsync is available on server"
              rsync --version | head -1
            else
              echo "⚠️ rsync not found on server, installing..."
              sudo apt-get update
              sudo apt-get install -y rsync
              echo "✅ rsync installed on server"
            fi
          EOF 